<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header') ?>
<?php

$users = Data::get('user')?>
<?php ErrMgr::attach($users) ?>


<!-- container -->
<div class="container">

    <div class="row">

        <!-- Article main content -->
        <article class="col-xs-12 maincontent">
            <header class="page-header">
                <h1 class="page-title">Registar/ Criar um novo utilizador</h1>
            </header>

            <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <hr>
                        <form method="post" action="<?=Url::toRoute('user/store')?>">
                            <div class="top-margin">
                                <label>Name Completo<span class="text-danger">*</span></label>
                                <input type="text" value="<?=$users->name?>" name="name" class="form-control" placeholder="Enter name">
                                <?= ErrMgr::bind('nomecompleto') ?>

                            </div>
                            <hr>
                            <div class="top-margin">
                                <label>Data de Nascimento <span class="text-danger">*</span></label>
                                <input type="datetime-local" value="<?=$users->datanascimento?>" name="dataNascimento" class="form-control" placeholder="Enter data de nascimento">
                                <?= ErrMgr::bind('dtanascimento') ?>
                            </div>
                            <hr>
                            <div class="top-margin">
                                <label>Email <span class="text-danger">*</span></label>
                                <input type="text" value="<?=$users->email?>" name="email" class="form-control" placeholder="Enter email">
                                <?= ErrMgr::bind('email') ?>
                            </div>
                            <hr>
                            <div class="top-margin">
                                <label>Contacto <span class="text-danger">*</span></label>
                                <input type="text" value="<?=$users->telefone?>" name="contacto" class="form-control" placeholder="Enter numero de telefone">
                                <?= ErrMgr::bind('telefone') ?>
                            </div>
                            <hr>
                            <div class="top-margin">
                                <label>Username <span class="text-danger">*</span></label>
                                <input type="text" value="<?=$users->username?>" name="username" class="form-control" placeholder="Enter um username">
                                <?= ErrMgr::bind('username') ?>
                            </div>

                            <hr>

                            <div class="top-margin">
                                <label>Password <span class="text-danger">*</span></label>
                                <input type="text" value="<?=$users->password?>" name="password" class="form-control" placeholder="Enter uma password">
                                <?= ErrMgr::bind('password') ?>
                            </div>

                            <hr>

                            <div class="col-lg-4 text-right">
                                <button class="btn btn-action" type="submit">New</button>
                            </div>
                    </div>
                    </form>
                </div>
            </div>

    </div>

    </article>
    <!-- /Article -->

</div>
</div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>

