<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header') ?>
<?php $users = Data::get('airport')?>
<?php ErrMgr::attach($users) ?>


	<!-- container -->
	<div class="container">

		<ol class="breadcrumb">
			<li><a href="../../../middleware/frontcontroller.php">Home</a></li>
			<li class="active">User access</li>
		</ol>

		<div class="row">
			
			<!-- Article main content -->
			<article class="col-xs-12 maincontent">
				<header class="page-header">
					<h1 class="page-title">Sign in</h1>
				</header>
				
				<div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
					<div class="panel panel-default">
						<div class="panel-body">
							<h3 class="thin text-center">Sign in to your account</h3>
							<p class="text-center text-muted">Se ainda não está registado, clique no botão disponivel. </p>
                            <p>
                                <a href="<?=Url::toRoute('user/create')?>" class="btn btn-info" role="button">Registar</a>
                            </p>
							<hr>
							
							<form method="post" action="<?=Url::toRoute('user/login')?>">
								<div class="top-margin">
									<label>Username<span class="text-danger">*</span></label>
									<input type="text" value="<?=$users->username?>" class="form-control" name="username">
								</div>
								<div class="top-margin">
									<label>Password <span class="text-danger">*</span></label>
									<input type="password" value="<?=$users->password?>" class="form-control" name="password">
								</div>

								<hr>

								<div class="row">
									<div class="col-lg-8">
										<b><a href="">Forgot password?</a></b>
									</div>
									<div class="col-lg-4 text-right">
										<button class="btn btn-action" type="submit">Sign in</button>
									</div>
								</div>
							</form>
						</div>
					</div>

				</div>
				
			</article>
			<!-- /Article -->

		</div>
	</div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>