<?php
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header') ?>
<?php

$airports = Data::get('airport')?>
<?php ErrMgr::attach($airports) ?>


<!-- container -->
<div class="container">

    <div class="row">

        <!-- Article main content -->
        <article class="col-xs-12 maincontent">
            <header class="page-header">
                <h1 class="page-title">Bilhetes</h1>
            </header>

            <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <hr>
                        <form method="post" action="<?=Url::toRoute('airport/store')?>">
                           < div class="top-margin">
                                <label>Nome <span class="text-danger">*</span></label>
                                <input type="text" value="<?=$airports->nome?>" name="nome" class="form-control" placeholder="Nome do Aeroporto">
                                <?= ErrMgr::bind('nomeAeroporto') ?>

                            </div>
                            <hr>
                            <div class="top-margin">
                                <label>Localização <span class="text-danger">*</span></label>
                                <input type="text" value="<?=$airports->localidade?>" name="localização" class="form-control" placeholder="Localização do Aeroporto">
                                <?= ErrMgr::bind('localidadeAeroporto') ?>
                            </div>
                    </div>
                    </form>
                </div>
            </div>

    </div>

    </article>
    <!-- /Article -->

</div>
</div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>

