<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header') ?>
<?php $airports = Data::get('airport') ?>
<?php ErrMgr::attach($airports) ?>

    <!-- container -->
    <div class="container">

        <div class="row">

            <!-- Article main content -->
            <article class="col-xs-12 maincontent">
                <header class="page-header">
                    <h1 class="page-title">Editar Aeroportos</h1>
                </header>


                <div class="panel panel-default">
                    <div class="panel-body">

                        <hr>


                        <form class="form-horizontal" method="post" action="<?=Url::toRoute('airport/update', $airports->id)?>">

                            <div class="form-group">
                                <label class="control-label col-sm-2" for="name">Nome:<span class="text-danger">*</span></label>
                                <div class="col-sm-6">
                                    <input type="text" value="<?=$airports->nome?>" class="form-control" required name="nome" placeholder="Nome do Aeroporto">
                                    <?= ErrMgr::bind('nomeAeroporto') ?>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-sm-2" for="name">Localidade:<span class="text-danger">*</span></label>
                                <div class="col-sm-6">
                                    <input type="text" required value="<?=$airports->localidade?>" class="form-control" name="localidade" placeholder="Localização de Aeroporto">
                                    <?= ErrMgr::bind('localidadeAeroporto') ?>
                                </div>
                            </div>


                            <hr>

                            <div class="col-lg-4 text-right">
                                <button class="btn btn-default" type="submit">Save</button>
                            </div>
                    </div>
                    </form>
                </div>
        </div>



        </article>
        <!-- /Article -->

    </div>
    </div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>