<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header') ?>
<?php $airports = Data::get('airport') ?>

<!-- container -->
<div class="container">

    <ol class="breadcrumb">
        <li><a href="index.html">Home</a></li>
        <li class="active">Airport Index</li>
    </ol>

    <h2 class="text-left top-space">Airport Index</h2>
    <h2 class="top-space"></h2>
    <div class="row">
        <div class="col-sm-12">
            <table class="table table-striped">
                <thead>
                <th>
                    <h3>Id</h3></th>
                <th><h3>Nome</h3>
                </th><th><h3>Localização</h3></th>
                </thead>
                <tbody>
                <?php foreach ($airports as $airport) { ?>
                    <tr>
                        <td><?=$airport->idAeroporto?></td>
                        <td><?=$airport->nome?></td>
                        <td><?=$airport->localidade?></td>
                        <td>
                            <a href="<?=Url::toRoute('airport/show', $airport->id)?>" class="btn btn-info" role="button">Show</a>
                            <a href="<?=Url::toRoute('airport/edit', $airport->id)?>" class="btn btn-info" role="button">Edit</a>
                            <a href="<?=Url::toRoute('airport/destroy', $airport->id)?>" class="btn btn-warning" role="button">Delete</a>

                        </td>
                    </tr>
                <?php } ?>

                </tbody>

            </table>

        </div>
        <div class="col-sm-6">
            <h3>Create a new Airport</h3>
            <p>
                <a href="<?=Url::toRoute('airport/create')?>" class="btn btn-info" role="button">New</a>
            </p>
        </div>
    </div> <!-- /row -->

</div>	<!-- /container -->
<?php Layout::includeLayout('footer')?>


