<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header') ?>
<?php $flights = Data::get('flight') ?>

<!-- container -->
<div class="container">

    <ol class="breadcrumb">
        <li><a href="<?= URL::toRoute('home/index')?>">Home</a></li>
        <li class="active">Voo Index</li>
    </ol>

    <h2 class="text-left top-space">Voo Index</h2>
    <h2 class="top-space"></h2>
    <div class="row">
        <div class="col-sm-12">
            <table class="table table-striped">
                <thead>
                <th>
                    <h3>Id do Voo</h3></th>
                <th><h3>Aeroporto</h3>
                </th><th><h3>Preço</h3></th>
                </thead>
                <tbody>
                <?php foreach ($flights as $flight) { ?>
                    <tr>
                        <td><?=$flight->id?></td>
                        <td><?=$flight->idaeroporto?></td>
                        <td><?=$flight->precovoo?></td>
                        <td>

                            <a href="<?=Url::toRoute('flight/show', $flight->id)?>" class="btn btn-info" role="button">Show</a>
                            <a href="<?=Url::toRoute('flight/edit', $flight->id)?>" class="btn btn-info" role="button">Edit</a>
                            <a href="<?=Url::toRoute('flight/destroy', $flight->id)?>" class="btn btn-warning" role="button">Delete</a>

                        </td>
                    </tr>
                <?php } ?>

                </tbody>

            </table>

        </div>
        <div class="col-sm-6">
            <h3>Criar/Introduzir um novo Voo</h3>
            <p>
                <a href="<?=Url::toRoute('flight/create')?>" class="btn btn-info" role="button">New</a>
            </p>
        </div>
    </div> <!-- /row -->

</div>	<!-- /container -->
<?php Layout::includeLayout('footer')?>
