<?php
use ArmoredCore\Controllers\BaseController;
use ArmoredCore\Interfaces\ResourceControllerInterface;
use ArmoredCore\WebObjects\Post;
use ArmoredCore\WebObjects\Redirect;
use ArmoredCore\WebObjects\View;

/*
class FinanceController extends BaseController
{
    /**
     * CRUD Resource Controller for ActiveRecord Model Finance
     *
     * Code generated by WebLogicMVC Code Builder
     *
     * Date: 2021-05-06
     *
     * WL Code Builder developed by Sílvio Priem Mendes
     * *
     */
class FinanceController extends BaseController implements ResourceControllerInterface
{
    /**
     * Returns index view with all records
     */


    public function index()
    {
        $finances = Finance::all();
        return View::make('finances.index', ['finances' => $finances]);
    }


    /**
     * Returns a view with a form to create a new record
     */
    public function create()
    {
        return View::make('finances.create');
    }


    /**
     * Receives new record data through POST method and stores it in the DB table
     */
    public function store()
    {
        //create new resource (activerecord/model) instance with data from POST
        //your form name fields must match the ones of the table fields
        $finance = new Finance(Post::getAll());

        if($finance->is_valid()){
            $finance->save();
            Redirect::toRoute('finance/index');
        } else {
            //redirect to form with data and errors
            Redirect::flashToRoute('finance/create', ['finance' => $finance]);
        }
    }


    /**
     * return a detailed view with record where PK = $id
     */
    public function show($id)
    {
        $finances = Finance::find([$id]);

        if (is_null($finances)) {
            //TODO redirect to standard error page
        } else {
            return View::make('finances.show', ['finances' => $finances]);
        }
    }


    /**
     * return a editable form view with record where PK = $id
     */
    public function edit($id)
    {
        $finance = Finance::find([$id]);

        if (is_null($finance)) {
            //TODO redirect to standard error page
        } else {
            return View::make('finance.edit', ['finance' => $finance]);
        }
    }


    /**
     * Receives record data through POST method and updates it in the DB table
     */
    public function update($id)
    {
        //find resource (activerecord/model) instance where PK = $id
        //your form name fields must match the ones of the table fields
        $finance = Finance::find([$id]);
        $finance->update_attributes(Post::getAll());

        if($finance->is_valid()){
            $finance->save();
            Redirect::toRoute('finance/index');
        } else {
            //redirect to form with data and errors
            Redirect::flashToRoute('finance/edit', ['finance' => $finance]);
        }
    }


    /**
     * deletes the record where PK = $id
     */
    public function destroy($id)
    {
        $finance = finance::find([$id]);
        $finance->delete();
        Redirect::toRoute('finance/index');
    }
//}
}