<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header') ?>
<?php

$tickets = Data::get('ticket')?>
<?php ErrMgr::attach($tickets) ?>


<!-- container -->
<div class="container">

    <div class="row">

        <!-- Article main content -->
        <article class="col-xs-12 maincontent">
            <header class="page-header">
                <h1 class="page-title">Bilhetes</h1>
            </header>

            <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <hr>
                        <form method="post" action="<?=Url::toRoute('ticket/store')?>">
                            <div class="top-margin">
                                <label>Preço <span class="text-danger">*</span></label>
                                <input type="text" value="<?=$tickets->preco?>" name="preco" class="form-control" placeholder="Enter preço da passagem">
                                <?= ErrMgr::bind('precoPassagem') ?>

                            </div>
                            <hr>
                            <div class="top-margin">
                                <label>Data e hora da compra do bilhete <span class="text-danger">*</span></label>
                                <input type="datetime-local" value="<?=$tickets->dtaHoraPassagemCompra?>" name="dataHora" class="form-control" placeholder="Enter pagamento">
                                <?= ErrMgr::bind('dtahorapassagemcompra') ?>
                            </div>
                            <hr>
                            <div class="top-margin">
                                <label>Ida <span class="text-danger">*</span></label>
                                <input type="text" value="<?=$tickets->idVooIda?>" name="VooIda" class="form-control" placeholder="Enter se é um voo de ida">
                                <?= ErrMgr::bind('idVooIda') ?>
                            </div>

                            <hr>

                            <div class="top-margin">
                                <label>Volta <span class="text-danger">*</span></label>
                                <input type="text" value="<?=$tickets->idVooVolta?>" name="VooVolta" class="form-control" placeholder="Enter se é um voo de ida e volta">
                                <?= ErrMgr::bind('idVooVolta') ?>
                            </div>
                            <hr>
                            <div class="col-lg-4 text-right">
                                <button class="btn btn-action" type="submit">New</button>
                            </div>
                    </div>
                    </form>
                </div>
            </div>

    </div>

    </article>
    <!-- /Article -->

</div>
</div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>

