<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header') ?>
<?php $ticktes = Data::get('ticket') ?>

<!-- container -->
<div class="container">

    <ol class="breadcrumb">
        <li><a href="index.html">Home</a></li>
        <li class="active">Book Index</li>
    </ol>

    <h2 class="text-left top-space">Book Index</h2>
    <h2 class="top-space"></h2>
    <div class="row">
        <div class="col-sm-12">
            <table class="table table-striped">
                <thead>
                <th>
                    <h3>Id</h3></th>
                <th><h3>data</h3>
                </th><th><h3>valor</h3></th>
                </thead>
                <tbody>
                <?php foreach ($ticktes as $tickte) { ?>
                    <tr>
                        <td><?=$tickte->idBilhete?></td>
                        <td><?=$tickte->preco?></td>
                        <td><?=$tickte->dataHoraCompraPassagem?></td>
                        <td><?=$tickte->Checkin?></td>
                        <td><?=$tickte->VooVolta?></td>
                        <td><?=$tickte->VooIda?></td>
                        <td>

                            <a href="<?=Url::toRoute('ticket/show', $tickte->id)?>" class="btn btn-info" role="button">Show</a>
                            <a href="<?=Url::toRoute('ticket/edit', $tickte->id)?>" class="btn btn-info" role="button">Edit</a>
                            <a href="<?=Url::toRoute('ticket/destroy', $tickte->id)?>" class="btn btn-warning" role="button">Delete</a>

                        </td>
                    </tr>
                <?php } ?>

                </tbody>

            </table>

        </div>
        <div class="col-sm-6">
            <h3>Create a new Book</h3>
            <p>
                <a href="<?=Url::toRoute('ticket/create')?>" class="btn btn-info" role="button">New</a>
            </p>
        </div>
    </div> <!-- /row -->

</div>	<!-- /container -->
<?php Layout::includeLayout('footer')?>


