<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header') ?>
<?php $tickets = Data::get('ticket') ?>

<!-- container -->
<div class="container">

    <div class="row">

        <!-- Article main content -->
        <article class="col-xs-12 maincontent">
            <header class="page-header">
                <h1 class="page-title">View Book</h1>
            </header>

            <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <hr>

                        <form method="post" action="<?=Url::toRoute('ticket/index')?>">
                            <div class="top-margin">
                                <label>ID <span class="text-danger">*</span></label>
                                <input readonly="true" type="text" value="<?=$tickets->idticket?>" name="id" class="form-control">
                            </div>
                            <div class="top-margin">
                                <label>Preço da Passagem <span class="text-danger">*</span></label>
                                <input readonly="true" type="text" value="<?=$tickets->precoPagassagem?>" name="preco" class="form-control">
                            </div>
                            <div class="top-margin">
                                <label>Data e hora da compra da passagem <span class="text-danger">*</span></label>
                                <input readonly="true" type="text" value="<?=$tickets->dtaHoraPassagemCompra?>" name="compraBilhete" class="form-control">
                            </div>
                            <div class="top-margin">
                                <label> Utilizador <span class="text-danger">*</span></label>
                                <input readonly="true" type="text" value="<?=$tickets->idUtilizador?>" name="utilizador" class="form-control">
                            </div>
                            <div class="top-margin">
                                <label>Ida <span class="text-danger">*</span></label>
                                <input readonly="true" type="text" value="<?=$tickets->idVooIda?>" name="IdaVoo" class="form-control">
                            </div>

                            <div class="top-margin">
                                <label>Volta <span class="text-danger">*</span></label>
                                <input readonly="true" type="text" value="<?=$tickets->idVooVolta?>" name="VoltaVoo" class="form-control">
                            </div>

                            <div>
                                <label>Check-In <span class="text-danger">*</span></label>
                                <input readonly="true" type="text" value="<?=$tickets->Ckeckin?>" name="CheckIn" class="form-control">
                                <select class="colemn">

                                    <option value="S"> Sim</option>
                                    <option value="N">Não</option>
                                </select>
                            </div>
                            <hr>

                            <div class="col-lg-4 text-right">
                                <button class="btn btn-action" type="submit">Return</button>
                            </div>
                    </div>
                    </form>
                </div>
            </div>

    </div>

    </article>
    <!-- /Article -->

</div>
</div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>

