<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
Layout::includeLayout('header'); ?>

    <!-- Header -->
    <header id="head">
        <div class="container">
            <div class="row">
                <h1 class="lead"><b>Flight Travel Air</b><br><small><b>Onde</b>Econtra voos</small><br>à sua medida</h1>


            </div>
        </div>
    </header>
    <!-- /Header -->

    <div class="jumbotron top-space">
        <h5><span class="glyphicon glyphicon-cog">&nbsp;</span><strong>Pesquisa Aqui: </strong>
            De  acordo com o indicado
        </h5>
    </div>

    <!-- Intro -->
    <div class="container text-center">
        <br>

        <form  method="post" action="<?=Url::toRoute('airport/index')?>">

            <tr>
                <td><label>Ida/volta: </label></td>
                <td><select class="column">

                    <option value="Sim"> Sim, de ida e volta</option>
                    <option value="Nao">Não, só de ida</option>
                </select></td>
            </tr>

            <tr>
              <td>  <label>Origem do voo</label></td>
                <td><input type="text" name="PesquisarVooOrigem" placeholder="indique a origem" value="<?php if(isset($_GET["pesquisar"])) echo $_GET["pesquisar"]; ?>"></td>

            </tr>

            <tr>

                <td><label>Destino do voo</label></td>
                <td><input type="text" name="PesquisarVooDestino" placeholder="indique o destino"></td>

            </tr>

            <tr>

                <td><label>Partida</label></td>
                <td><input type="date" name="dataPartida" placeholder="indique o destino"></td>

            </tr>

            <tr>

                <td><label>Retorno</label></td>
                <td><input type="date" name="dataRetorno" placeholder="indique o destino"></td>

            </tr>
                <br>
            <br>

                <div class="text-center">
                <button class="btn btn-action" name="pesquisar" type="submit">Pesquisar</button>
                </div>
                <br>
        </form>
        <br>

        <div class="table-responsive">
            <table  class="table table-bordered">
                <tr>
                    <th>Aviao</th>
                    <th>Aeroporto</th>
                    <th>Preço</th>

                </tr>


                <?php
                //$pesquisar = setsession();
                if(isset($_POST["pesquisar"]))
                {

                    $pesquisar = Session::get('pesquisar');
                    $airport = Airport::find_by_nome('pesquisar');
                    $flights = Flight::find_by_precovoo('pesquisar');

                    //$plane = Plane::
                    // $sql_query = "SELECT * FROM flight WHERE idvooorigem like '%".$_GET["pesquisar"]."%'";
                    //$result = mysqli_query($flights);

                    if($airport > 0)
                    {
                        while ($row = $airport->fetch())
                        {
                            echo '<tr><td>'.$row.'</td></tr>';
                        }
                    }
                    if($flights > 0)
                    {
                        while ($row = $flights->fetch())
                        {
                            echo '<tr><td>'.$row.'</td></tr>';
                        }
                    }
                    else
                    {
                        echo '<label>Não foram encontrados resultados</label>';
                    }
                }
                ?>


            </table>
        </div>
    </div>
    <!-- /Intro-->



    </div>

    <!-- Highlights - jumbotron -->
    <div class="jumbotron top-space">
        <div class="container">
            <h3 class="text-center thin">Destinos Possiveis</h3>
            <div class="row">
                <div class="col-md-3 col-sm-6 highlight">

                    <img src="<?= Asset::image('destino_1')?>" alt="Voo"></a>
                    <div class="h-body text-center">
                        <p></p>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6 highlight">

                    <img src="<?= Asset::image('destino_2')?>" alt="Voo"></a>
                    <div class="h-body text-center">
                        <p></p>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6 highlight">

                    <img src="<?= Asset::image('desyino_3')?>" alt="Voo"></a>
                    <div class="h-body text-center">
                        <p></p>
                    </div>
                </div>
                 <!-- /row  -->

        </div>
    </div>
    <!-- /Highlights -->



</div>	<!-- /container -->

<?php Layout::includeLayout('footer')?>