<?php
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header') ?>
<?php $planes = Data::get('plane')?>
<?php ErrMgr::attach($planes) ?>


<!-- container -->
<div class="container">

    <div class="row">

        <!-- Article main content -->
        <article class="col-xs-12 maincontent">
            <header class="page-header">
                <h1 class="page-title">Aviões</h1>
            </header>

            <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <hr>
                        <form method="post" action="<?=Url::toRoute('plane/store')?>">
                           <div class="top-margin">
                                <label>Nome <span class="text-danger">*</span></label>
                                <input type="text" value="<?=$planes->nome?>" name="nome" class="form-control" placeholder="Nome do Avião">
                                <?= ErrMgr::bind('nomeaviao') ?>

                            </div>
                            <div class="top-margin">
                                <label>Referência <span class="text-danger">*</span></label>
                                <input type="text" value="<?=$planes->referencia?>" name="referencia" class="form-control" placeholder="Referência do Avião">
                                <?= ErrMgr::bind('referenciaaviao') ?>
                            </div>
                            <div class="top-margin">
                                <label>Lotação <span class="text-danger">*</span></label>
                                <input type="text" value="<?=$planes->lotacao?>" name="lotacao" class="form-control" placeholder="Lotação do Avião">
                                <?= ErrMgr::bind('lotacaoaviao') ?>
                            </div>
                    </div>
                    <div class="col-lg-4 text-right">
                        <button class="btn btn-action" type="submit">New</button>
                    </div>
                    </form>
                </div>
            </div>

    </div>

    </article>
    <!-- /Article -->

</div>

<?php Layout::includeLayout('footer') ?>

